# ConstructYaml.msg

# List of names for the poses
string[] pose_names

# Corresponding list of PoseStamped messages
geometry_msgs/PoseStamped[] poses
geometry_msgs/Pose[] scene_poses

# waypoints_mode, service_mode, patrol_mode, path_mode
# goal_mode ( use with ros2 run commands in command), eraser_mode
# get_wp_list, get_srv_list, get_patrol_list, get_path_list
string mode
bool loop

# Three ros2 run commands , use with goal_mode
# ros2 run rom_robot_autonomy autonomy_waypoints_mode_w_cancel
# ros2 run rom_robot_autonomy autonomy_patrol_mode_w_cancel
# ros2 run rom_robot_autonomy autonomy_service_mode_w_cancel 
# ros2 run rom_waypoints_provider path_runner
string command
---
string[] pose_names

# Corresponding list of PoseStamped messages
geometry_msgs/PoseStamped[] poses
geometry_msgs/Pose[] scene_poses

int16 status         # 1 [ok] | -1 [not ok]