# call_from_table | video | sound | setting | save_setting | reboot | poweroff
# ai_task1 | ai_task2 | voice_command | save_ai_api_key | get_ai_api_key | other_task2 
string request_string
string request_settings
string str_reserve2
float64 float_reserve1
float64 float_reserve2
---
string[] str_reserve_vector
string response_settings
int16 status      


# RETURN STATUS
#  1 [],  setting read success
# -1 [], setting read error

#  2 [], setting write success
# -2 [], setting write error

#  3 [], reboot success
#  4 [], poweroff success

#  5 [], voice_command ok
# -5 [], voice_command unknown

#  6 [], save_ai_api_key_ok
# -6 [], save_ai_api_key_error

#  7 [], get_ai_api_key_ok
# -7 [], get_ai_api_key_error
